# ##############################################################################
#
# This script compiles the Mofo Wallet source code for the various 
# supported nodewebkit platforms.
# 
# Supported platforms:
#
#   1. Windows (mofo.win.zip)
#   2. Linux   (mofo.lin.zip
#   3. MacOSX  (mofo.osx.zip)
#
# Requirements:
#
#   1. Compiled FIMK jar files (run compile.sh first)
#   2. Unpacked NXT jar files in dist/nxt
#   2. Installed grunt
#   3. Installed grunt nodewebkit
#
# Usage:
#
#   Usage is straightforward, just run this script and you'll end up with 
#   executables for all supported platforms. All platforms come with various 
#   helper libraries that for the embedded webkit libraries, these libraries 
#   (dll, so) are packaged together with the FIM Community Client source in 
#   a directory. That directory is then zipped. 
#
# ##############################################################################
DEBUG=false
WITH_NEXT=true
VERSION=`cat VERSION`
BASE=mofowallet
MODE_JS_FILE='app/mode.js'
MODE_JS=$(cat <<'END_HEREDOC'
/* This file is autogenerated by the build system */
var VERSION='#VERSION#';
var ENABLE_DUAL_ENGINES=true;
var IS_TEST_NET=false;
var FORCE_LOCAL_HOST=false;
var PRIVATE_ENABLED=false;
var WALLET_NAME='Lompsa.com';
var TRADE_UI_ONLY=false;
var DEBUG=false;
END_HEREDOC
)
cat > $MODE_JS_FILE <<EOF
$MODE_JS
EOF
orig=#VERSION#
sed -i "s/${orig}/${VERSION}/g" $MODE_JS_FILE

grunt nodewebkit

# This compiles NXT
# if [ "$WITH_NEXT" = "true" ]; then
#   cd ../nxt
#   sh compile.sh
#   cd ../mofowallet
# fi

/bin/rm -r -f dist/build/linux32

if [ "$DEBUG" = "false" ]; then
  /bin/rm -r -f dist/build/linux64
  /bin/rm -r -f dist/build/win32
  /bin/rm -r -f dist/build/win64
  /bin/rm -r -f dist/build/osx32
  /bin/rm -r -f dist/build/osx64
fi

mkdir dist/releases

echo "nodewebkit generated successfully"

FIM_FILES="../fimk/html/ ../fimk/lib/ ../fimk/fim.jar ../fimk/MIT-license.txt ../fimk/README.txt ../fimk/run.bat ../fimk/run.sh"
FIM_FILES_CONF="../fimk/conf/nxt-default.properties ../fimk/conf/logging-default.properties"

NXT_FILES="../nxt-plus/html/ ../nxt-plus/lib/ ../nxt-plus/nxt.jar ../nxt-plus/MIT-license.txt ../nxt-plus/README.txt ../nxt-plus/run.bat ../nxt-plus/run.sh"
NXT_FILES_CONF="../nxt-plus/conf/nxt-default.properties ../nxt-plus/conf/logging-default.properties"

# ==============================================================================
# Linux 32
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/linux32
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/fim
mkdir -p $BUILD/fim/conf
cp -r -p $FIM_FILES $BUILD/fim
cp -p $FIM_FILES_CONF $BUILD/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/nxt
  mkdir -p $BUILD/nxt/conf
  cp -r -p $NXT_FILES $BUILD/nxt
  cp -p $NXT_FILES_CONF $BUILD/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/linux32/* $BUILD

if [ "$DEBUG" = "true" ]; then
  exit 0
fi

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.linux32-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.linux32-$VERSION.zip .
cd ../../..

echo "$BASE.linux32-$VERSION.zip generated successfully"

# ==============================================================================
# Linux 64
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/linux64
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/fim
mkdir -p $BUILD/fim/conf
cp -r -p $FIM_FILES $BUILD/fim
cp -p $FIM_FILES_CONF $BUILD/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/nxt
  mkdir -p $BUILD/nxt/conf
  cp -r -p $NXT_FILES $BUILD/nxt
  cp -p $NXT_FILES_CONF $BUILD/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/linux64/* $BUILD

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.linux64-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.linux64-$VERSION.zip .
cd ../../..

echo "$BASE.linux64-$VERSION.zip generated successfully"

# ==============================================================================
# Windows 32
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/win32
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/fim
mkdir -p $BUILD/fim/conf
cp -r -p $FIM_FILES $BUILD/fim
cp -p $FIM_FILES_CONF $BUILD/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/nxt
  mkdir -p $BUILD/nxt/conf
  cp -r -p $NXT_FILES $BUILD/nxt
  cp -p $NXT_FILES_CONF $BUILD/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/win32/* $BUILD

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.win32-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.win32-$VERSION.zip .
cd ../../..

echo "$BASE.win32-$VERSION.zip generated successfully"

# ==============================================================================
# Windows 64
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/win64
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/fim
mkdir -p $BUILD/fim/conf
cp -r -p $FIM_FILES $BUILD/fim
cp -p $FIM_FILES_CONF $BUILD/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/nxt
  mkdir -p $BUILD/nxt/conf
  cp -r -p $NXT_FILES $BUILD/nxt
  cp -p $NXT_FILES_CONF $BUILD/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/win64/* $BUILD

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.win64-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.win64-$VERSION.zip .
cd ../../..

echo "$BASE.win64-$VERSION.zip generated successfully"

# ==============================================================================
# Osx 32 (10.7 and up)
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/osx32
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/mofowallet.app/Contents/Resources/fim
mkdir -p $BUILD/mofowallet.app/Contents/Resources/fim/conf
cp -r -p $FIM_FILES $BUILD/mofowallet.app/Contents/Resources/fim
cp -p $FIM_FILES_CONF $BUILD/mofowallet.app/Contents/Resources/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/mofowallet.app/Contents/Resources/nxt
  mkdir -p $BUILD/mofowallet.app/Contents/Resources/nxt/conf
  cp -r -p $NXT_FILES $BUILD/mofowallet.app/Contents/Resources/nxt
  cp -p $NXT_FILES_CONF $BUILD/mofowallet.app/Contents/Resources/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/osx32/* $BUILD

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.osx32-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.osx32-$VERSION.zip .
cd ../../..

echo "$BASE.osx32-$VERSION generated successfully"

# ==============================================================================
# Osx 64 (10.7 and up)
# ==============================================================================

# Copy FIM to the fim dir to allow addition of other servers later
BUILD=dist/build/osx64
mkdir -p $BUILD

# FIM embedded in mofowallet
mkdir -p $BUILD/mofowallet.app/Contents/Resources/fim
mkdir -p $BUILD/mofowallet.app/Contents/Resources/fim/conf
cp -r -p $FIM_FILES $BUILD/mofowallet.app/Contents/Resources/fim
cp -p $FIM_FILES_CONF $BUILD/mofowallet.app/Contents/Resources/fim/conf

# NXT embedded in mofowallet
if [ "$WITH_NEXT" = "true" ]; then
  mkdir -p $BUILD/mofowallet.app/Contents/Resources/nxt
  mkdir -p $BUILD/mofowallet.app/Contents/Resources/nxt/conf
  cp -r -p $NXT_FILES $BUILD/mofowallet.app/Contents/Resources/nxt
  cp -p $NXT_FILES_CONF $BUILD/mofowallet.app/Contents/Resources/nxt/conf
fi

# Copy over the mofowallet files
cp -r -p dist/mofowallet/osx64/* $BUILD

# create the release zip
cd $BUILD
/bin/rm -f ../../../dist/releases/$BASE.osx64-$VERSION.zip
zip -qr -9 ../../../dist/releases/$BASE.osx64-$VERSION.zip .
cd ../../..

echo "$BASE.osx64-$VERSION generated successfully"

# ==============================================================================
# Package it all up
# ==============================================================================

DATE=`date +%Y-%m-%d`

TARGET_WIN32="$BASE.win32-$VERSION.zip"
TARGET_WIN64="$BASE.win64-$VERSION.zip"
TARGET_MAC32="$BASE.osx32-$VERSION.zip"
TARGET_MAC64="$BASE.osx64-$VERSION.zip"
TARGET_LIN32="$BASE.linux32-$VERSION.zip"
TARGET_LIN64="$BASE.linux64-$VERSION.zip"

# The version number is used to pick up the changelog which describes the release
CHANGELOG="changelogs/mofowallet-$VERSION.txt"
ANNOUNCEMENT="announcements/mofowallet-$VERSION.txt"

rm -f $ANNOUNCEMENT

SHA_SUM_1=`sha256sum "dist/releases/$TARGET_WIN32"`
MD5_SUM_1=`md5sum "dist/releases/$TARGET_WIN32"`
SHA_SUM_1=${SHA_SUM_1%\ *}
MD5_SUM_1=${MD5_SUM_1%\ *}

SHA_SUM_2=`sha256sum "dist/releases/$TARGET_WIN64"`
MD5_SUM_2=`md5sum "dist/releases/$TARGET_WIN64"`
SHA_SUM_2=${SHA_SUM_2%\ *}
MD5_SUM_2=${MD5_SUM_2%\ *}

SHA_SUM_3=`sha256sum "dist/releases/$TARGET_MAC32"`
MD5_SUM_3=`md5sum "dist/releases/$TARGET_MAC32"`
SHA_SUM_3=${SHA_SUM_3%\ *}
MD5_SUM_3=${MD5_SUM_3%\ *}

SHA_SUM_4=`sha256sum "dist/releases/$TARGET_MAC64"`
MD5_SUM_4=`md5sum "dist/releases/$TARGET_MAC64"`
SHA_SUM_4=${SHA_SUM_4%\ *}
MD5_SUM_4=${MD5_SUM_4%\ *}

SHA_SUM_5=`sha256sum "dist/releases/$TARGET_LIN32"`
MD5_SUM_5=`md5sum "dist/releases/$TARGET_LIN32"`
SHA_SUM_5=${SHA_SUM_5%\ *}
MD5_SUM_5=${MD5_SUM_5%\ *}

SHA_SUM_6=`sha256sum "dist/releases/$TARGET_LIN64"`
MD5_SUM_6=`md5sum "dist/releases/$TARGET_LIN64"`
SHA_SUM_6=${SHA_SUM_6%\ *}
MD5_SUM_6=${MD5_SUM_6%\ *}

BANNER=$(cat <<'END_HEREDOC'
 /$$$$$$$$ /$$$$$$ /$$      /$$          Release : #VERSION#          
| $$_____/|_  $$_/| $$$    /$$$          Date    : #DATE#          
| $$        | $$  | $$$$  /$$$$                  
| $$$$$     | $$  | $$ $$/$$ $$          http://fimk.fi       
| $$__/     | $$  | $$  $$$| $$          http://mofowallet.com
| $$        | $$  | $$\  $ | $$          http://forum.fimk.fi          
| $$       /$$$$$$| $$ \/  | $$          https://github.com/fimkrypto/mofowallet
|__/      |______/|__/     |__/                 
                     /$$                                       /$$              
                    | $$                                      | $$              
                    | $$   /$$  /$$$$$$  /$$   /$$  /$$$$$$  /$$$$$$    /$$$$$$ 
                    | $$  /$$/ /$$__  $$| $$  | $$ /$$__  $$|_  $$_/   /$$__  $$
                    | $$$$$$/ | $$  \__/| $$  | $$| $$  \ $$  | $$    | $$  \ $$
                    | $$_  $$ | $$      | $$  | $$| $$  | $$  | $$ /$$| $$  | $$
                    | $$ \  $$| $$      |  $$$$$$$| $$$$$$$/  |  $$$$/|  $$$$$$/
                    |__/  \__/|__/       \____  $$| $$____/    \___/   \______/ 
                                         /$$  | $$| $$                          
                                        |  $$$$$$/| $$                          
                                         \______/ |__/            


                                presents:


             /$$      /$$            /$$$$$$                               
            | $$$    /$$$           /$$__  $$                              
            | $$$$  /$$$$  /$$$$$$ | $$  \__//$$$$$$                       
            | $$ $$/$$ $$ /$$__  $$| $$$$   /$$__  $$                      
            | $$  $$$| $$| $$  \ $$| $$_/  | $$  \ $$                      
            | $$\  $ | $$| $$  | $$| $$    | $$  | $$                      
            | $$ \/  | $$|  $$$$$$/| $$    |  $$$$$$/                      
            |__/     |__/ \______/ |__/     \______/                       
                                                                           
                                                                           
                                                                           
                         /$$      /$$           /$$ /$$             /$$    
                        | $$  /$ | $$          | $$| $$            | $$    
                        | $$ /$$$| $$  /$$$$$$ | $$| $$  /$$$$$$  /$$$$$$  
                        | $$/$$ $$ $$ |____  $$| $$| $$ /$$__  $$|_  $$_/  
                        | $$$$_  $$$$  /$$$$$$$| $$| $$| $$$$$$$$  | $$    
                        | $$$/ \  $$$ /$$__  $$| $$| $$| $$_____/  | $$ /$$
                        | $$/   \  $$|  $$$$$$$| $$| $$|  $$$$$$$  |  $$$$/
                        |__/     \__/ \_______/|__/|__/ \_______/   \___/  

END_HEREDOC
)

cat > $ANNOUNCEMENT <<EOF
$BANNER

`cat $CHANGELOG`



                             ~~~ DOWNLOAD ~~~

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_WIN32
 
SHA256 $SHA_SUM_1
MD5    $MD5_SUM_1

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_WIN64
 
SHA256 $SHA_SUM_2
MD5    $MD5_SUM_2

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_MAC32
 
SHA256 $SHA_SUM_3
MD5    $MD5_SUM_3

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_MAC64
 
SHA256 $SHA_SUM_4
MD5    $MD5_SUM_4

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_LIN32
 
SHA256 $SHA_SUM_5
MD5    $MD5_SUM_5

https://github.com/fimkrypto/mofowallet/releases/download/v$VERSION/$TARGET_LIN64
 
SHA256 $SHA_SUM_6
MD5    $MD5_SUM_6

EOF

orig=#VERSION#
sed -i "s/${orig}/${VERSION}/g" $ANNOUNCEMENT

orig=#DATE#
sed -i "s/${orig}/${DATE}/g" $ANNOUNCEMENT

if [ "$DEBUG" = "false" ]; then
  gpg --clearsign --batch $ANNOUNCEMENT
  mv $ANNOUNCEMENT.asc $ANNOUNCEMENT
fi

echo "========================================================================="
echo "== Successfully generated new version"
echo "=="
echo "=="
echo "== Checklist.."
echo "=="
echo "== 1. Did you update the version number in README.txt ?"
echo "== 2. Did you update the version number in index.html ?"
echo "=="
echo "== Final actions.."  
echo "=="
echo "== 1. Github release: https://github.com/fimkrypto/mofowallet/releases/tag/v$VERSION"
echo "=="
echo "=="
echo "========================================================================="