# ##############################################################################
#
# Builds lompsa TRADER demo web edition and publishes the result on lompsa.com
#
# ##############################################################################

echo "start building mofowallet"
VERSION=`cat VERSION`
MODE_JS_FILE='app/mode.js'
MODE_JS=$(cat <<'END_HEREDOC'
/* This file is autogenerated by the build system */
var VERSION='#VERSION#';
var ENABLE_DUAL_ENGINES=false;
var IS_TEST_NET=false;
var FORCE_LOCAL_HOST=false;
var TRADE_UI_ONLY=false;
var DEBUG=false;
var BUILD_TIMESTAMP=#TIMESTAMP#;
var WALLET_NAME='Lompsa.com';
END_HEREDOC
)
cat > $MODE_JS_FILE <<EOF
$MODE_JS
EOF
orig=#VERSION#
sed -i "s/${orig}/${VERSION}/g" $MODE_JS_FILE
orig=#TIMESTAMP#
timestamp=$(date +%s)
sed -i "s/${orig}/${timestamp}/g" $MODE_JS_FILE

grunt build
echo "successfully built mofowallet"

# copy over all code to lompsa server
#mv dist/index.html dist/index.htm
DATE=`date`
echo "<!--$DATE-->" >> dist/index.html
scp -r -P 33 dist/* root@78.46.176.8:/var/www/lompsa/docs