# ##############################################################################
#
# Builds mofowallet web edition and publishes the result on mofowallet.com
#
# ##############################################################################

echo "start building mofowallet"
VERSION=`cat VERSION`
MODE_JS_FILE='app/mode.js'
MODE_JS=$(cat <<'END_HEREDOC'
/* This file is autogenerated by the build system */
var VERSION='#VERSION#';
var ENABLE_DUAL_ENGINES=true;
var IS_TEST_NET=false;
var FORCE_LOCAL_HOST=false;
var PRIVATE_ENABLED=false;
var WALLET_NAME='Lompsa.com';
var TRADE_UI_ONLY=false;
var DEBUG=false;
END_HEREDOC
)
cat > $MODE_JS_FILE <<EOF
$MODE_JS
EOF
orig=#VERSION#
sed -i "s/${orig}/${VERSION}/g" $MODE_JS_FILE
grunt build
echo "successfully built mofowallet"

# copy over all code to git/mofo
echo "copy mofo files to jekyll repo"
MOFO_FILES="dist/fonts dist/images dist/partials dist/plugins dist/scripts dist/styles dist/favicon.ico dist/i18n dist/amstockchart dist/mode.js"
cp -r -p $MOFO_FILES ~/git/mofo
cp dist/index.html ~/git/mofo/launch.html
DATE=`date`
echo "<!--$DATE-->" >> ~/git/mofo/launch.html
echo "successfully copied mofo files to jekyll repo"

cd ~/git/mofo
echo "start jekyll build"
bundle exec jekyll build
echo "done"

git add --all
git commit -am 'Update mofo'
git push origin gh-pages