/* This file is autogenerated by the build system */
var VERSION='0.7.0';
var ENABLE_DUAL_ENGINES=false;
var IS_TEST_NET=false;
var FORCE_LOCAL_HOST=false;
var WALLET_NAME='FIMK';
var TRADE_UI_ONLY=false;
var DEBUG=false;
var BUILD_TIMESTAMP=1637333228;
