/* This file is autogenerated by the build system */
var VERSION='0.4.10';
var ENABLE_DUAL_ENGINES=false;
var IS_TEST_NET=window.location.port == "6886";
var FORCE_LOCAL_HOST=true;
var PRIVATE_ENABLED=IS_TEST_NET;
var WALLET_NAME='FIMKrypto';
var TRADE_UI_ONLY=false;
var DEBUG=false;
var BUILD_TIMESTAMP=0;
